/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyek4;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;
/**
 *
 * @author Farras Hilmy Zaidan
 */
public class FinalGUI extends javax.swing.JFrame {
    DefaultListModel<String> dlm;
    List<String> items = new ArrayList<>();
    Set<String> itemSet = new LinkedHashSet<>();
    Map<Integer, String> itemMap = new LinkedHashMap<>();
    String[] datas = {"buku", "meja", "kursi", "tas", "pintu jati", "tikus", "meja", "buku tulis", "tas"};
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FinalGUI.class.getName());

    /**
     * Creates new form FinalGUI
     */
    public FinalGUI() {
        initComponents();
        this.dlm = new DefaultListModel<>();
        this.jListItem.setModel(dlm);
        
        for(String data: datas){
            dlm.addElement(data);
        }
        updateAllLabel();
    }
    
    private void updateJumDataTersimpanList(){
        jLabelJumlahList.setText(
                "Data tersimpan = " + items.size());
    }

    private void updateJumDataTersimpanSet(){
        jLabelJumlahSet.setText(
                "Data tersimpan = " + itemSet.size());
    }

    private void updateJumDataTersimpanMap(){
        jLabelJumlahMap.setText(
                "Data tersimpan = " + itemMap.size());
    }

    private void updateAllLabel(){
        updateJumDataTersimpanList();
        updateJumDataTersimpanSet();
        updateJumDataTersimpanMap();
    }
    
    private void addItem(String namaItem){
        dlm.addElement(namaItem);
    }

    private void clearJList(){
        dlm.clear();
    }

    private void saveJListToList(){
        items.clear();
        for (int i = 0; i < dlm.size(); i++) {
            items.add(dlm.getElementAt(i));
        }
        updateJumDataTersimpanList();
    }

    private void saveJListToSet(){
        itemSet.clear();
        for (int i = 0; i < dlm.size(); i++) {
            itemSet.add(dlm.getElementAt(i));
        }
        updateJumDataTersimpanSet();
    }

    private void saveJListToMap(){
        itemMap.clear();
        for (int i = 0; i < dlm.size(); i++) {
            itemMap.put(i, dlm.getElementAt(i));
        }
        updateJumDataTersimpanMap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabelJumlahList = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnClearAll = new javax.swing.JButton();
        btnSaveList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        btnInsertList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldItem = new javax.swing.JTextField();
        jLabelJumlahSet = new javax.swing.JLabel();
        btnSaveSet = new javax.swing.JButton();
        btnInsertSet = new javax.swing.JButton();
        btnInsertMap = new javax.swing.JButton();
        btnSaveMap = new javax.swing.JButton();
        jLabelJumlahMap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAdd.setBackground(new java.awt.Color(102, 0, 102));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setLabel("add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnDelete.setBackground(new java.awt.Color(102, 0, 102));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setLabel("delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        jLabelJumlahList.setText("Data tersimpan : ");

        btnUpdate.setBackground(new java.awt.Color(102, 0, 102));
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnClearAll.setBackground(new java.awt.Color(102, 0, 102));
        btnClearAll.setForeground(new java.awt.Color(255, 255, 255));
        btnClearAll.setText("clear all");
        btnClearAll.addActionListener(this::btnClearAllActionPerformed);

        btnSaveList.setBackground(new java.awt.Color(102, 0, 102));
        btnSaveList.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveList.setText("Save to List ->");
        btnSaveList.addActionListener(this::btnSaveListActionPerformed);

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jListItem.setBackground(new java.awt.Color(0, 153, 153));
        jListItem.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jListItem);

        btnInsertList.setBackground(new java.awt.Color(102, 0, 102));
        btnInsertList.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertList.setText("<- Insert Data List");
        btnInsertList.addActionListener(this::btnInsertListActionPerformed);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Item Name :");

        jTextFieldItem.addActionListener(this::jTextFieldItemActionPerformed);

        jLabelJumlahSet.setText("Data tersimpan : ");

        btnSaveSet.setBackground(new java.awt.Color(102, 0, 102));
        btnSaveSet.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveSet.setText("Save to Set ->");
        btnSaveSet.addActionListener(this::btnSaveSetActionPerformed);

        btnInsertSet.setBackground(new java.awt.Color(102, 0, 102));
        btnInsertSet.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertSet.setText("<- Insert Data Set");
        btnInsertSet.addActionListener(this::btnInsertSetActionPerformed);

        btnInsertMap.setBackground(new java.awt.Color(102, 0, 102));
        btnInsertMap.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertMap.setText("<- Insert Data Map");
        btnInsertMap.addActionListener(this::btnInsertMapActionPerformed);

        btnSaveMap.setBackground(new java.awt.Color(102, 0, 102));
        btnSaveMap.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveMap.setText("Save to Map ->");
        btnSaveMap.addActionListener(this::btnSaveMapActionPerformed);

        jLabelJumlahMap.setText("Data tersimpan : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnClearAll, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldItem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnInsertList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(btnSaveList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelJumlahList, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnInsertSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSaveSet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelJumlahSet, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnInsertMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSaveMap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelJumlahMap, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJumlahList)
                            .addComponent(btnSaveList))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertList)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJumlahSet)
                            .addComponent(btnSaveSet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertSet)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelJumlahMap)
                            .addComponent(btnSaveMap))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearAll)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addItem(jTextFieldItem.getText());
        jTextFieldItem.setText("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int index = jListItem.getSelectedIndex();
        dlm.removeElementAt(index);
        jTextFieldItem.setText("");
        // deleteItem(); -> bisa jadi another option buat reusability code
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int index = jListItem.getSelectedIndex();
        String selected = jTextFieldItem.getText();
        dlm.setElementAt(selected, index);

        jTextFieldItem.setText("");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearAllActionPerformed
        clearJList();
    }//GEN-LAST:event_btnClearAllActionPerformed

    private void btnSaveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveListActionPerformed
        saveJListToList();
    }//GEN-LAST:event_btnSaveListActionPerformed

    private void btnInsertListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertListActionPerformed
        clearJList();
        for (String item : items) {
            addItem(item);
        }
    }//GEN-LAST:event_btnInsertListActionPerformed

    private void jTextFieldItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemActionPerformed

    private void btnSaveSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSetActionPerformed
        saveJListToSet();
    }//GEN-LAST:event_btnSaveSetActionPerformed

    private void btnInsertSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertSetActionPerformed
        clearJList();
        for (String item : itemSet) {
            addItem(item);
        }
    }//GEN-LAST:event_btnInsertSetActionPerformed

    private void btnInsertMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertMapActionPerformed
        clearJList();
        for (String item : itemMap.values()) {
            addItem(item);
        }
    }//GEN-LAST:event_btnInsertMapActionPerformed

    private void btnSaveMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMapActionPerformed
        saveJListToMap();
    }//GEN-LAST:event_btnSaveMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FinalGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClearAll;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsertList;
    private javax.swing.JButton btnInsertMap;
    private javax.swing.JButton btnInsertSet;
    private javax.swing.JButton btnSaveList;
    private javax.swing.JButton btnSaveMap;
    private javax.swing.JButton btnSaveSet;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelJumlahList;
    private javax.swing.JLabel jLabelJumlahMap;
    private javax.swing.JLabel jLabelJumlahSet;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldItem;
    // End of variables declaration//GEN-END:variables
}
